In [1]:
from super_trend_lib import SuperTrendRunner
import pymongo

client = pymongo.MongoClient("mongodb+srv://new_user:new_user@super-trend.xltbo.mongodb.net/?retryWrites=true&w=majority")
db = client['super-trend']

In [2]:
db['VTI'].delete_many({})

In [3]:
JSON_PATH = '/root/projects/supertrend'
super_trend_runner = SuperTrendRunner(ticker='VTI', json_path=JSON_PATH, multiplier=2.5, debug_mode=True, rolling_period=14, initial_amount=10000)
super_trend_df = super_trend_runner.initialize_dataframe()
super_trend_df

generating super trend for VTI starting 2022-07-07 00:00:00 and ending 2023-01-06 00:00:00

,Open,High,Low,Close,Volume,Dividends,Stock Splits,high-low,Previous Close,high-previous_close,...,average_true_range,high_low_avg,lower_band,higher_band,super_trend,final_higher_band,final_lower_band,buy_or_sell,portfolio_values,percentage_change
Date,,,,,,,,,,,,,,,,,,,,,
2022-07-07,190.895315,193.461988,190.855667,193.075500,2919300,0.0,0,2.606321,189.943970,3.518018,...,NaN,192.158827,NaN,NaN,NaN,NaN,NaN,None,10000.000000,0.0
2022-07-08,192.312445,193.937676,191.271898,192.877319,2799200,0.0,0,2.665778,193.075500,0.862175,...,NaN,192.604787,NaN,NaN,NaN,NaN,NaN,None,10000.000000,0.0
2022-07-11,191.638579,192.005242,190.082710,190.439468,3033800,0.0,0,1.922532,192.877319,-0.872077,...,NaN,191.043976,NaN,NaN,NaN,NaN,NaN,None,10000.000000,0.0
2022-07-12,190.271006,191.499845,187.892625,188.794418,2640300,0.0,0,3.607221,190.439468,1.060377,...,NaN,189.696235,NaN,NaN,NaN,NaN,NaN,None,10000.000000,0.0
2022-07-13,186.098899,189.369184,185.702507,187.971878,3322400,0.0,0,3.666678,188.794418,0.574766,...,NaN,187.535846,NaN,NaN,NaN,NaN,NaN,None,10000.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-30,190.179993,191.270004,189.279999,191.190002,5978800,0.0,0,1.990005,191.679993,-0.409988,...,3.304510,190.275002,182.013727,198.536276,197.776727,197.776727,184.295412,False,10212.168584,0.0
2023-01-03,192.380005,193.360001,188.929993,190.410004,4092500,0.0,0,4.430008,191.190002,2.169998,...,3.419765,191.144997,182.595584,199.694409,197.776727,197.776727,184.295412,False,10212.168584,0.0
2023-01-04,191.509995,193.059998,190.139999,192.100006,3852500,0.0,0,2.919998,190.410004,2.649994,...,3.194713,191.599998,183.613217,199.586780,197.776727,197.776727,184.295412,False,10212.168584,0.0
2023-01-05,191.220001,191.270004,189.460007,189.850006,4150000,0.0,0,1.809998,192.100006,-0.830002,...,3.007666,190.365005,182.845840,197.884171,197.776727,197.776727,184.295412,False,10212.168584,0.0
2023-01-06,191.119995,194.220001,189.860001,194.139999,2534725,0.0,0,4.360001,189.850006,4.369995,...,3.061056,192.040001,184.387360,199.692642,197.776727,197.776727,184.387360,False,10212.168584,0.0

In [7]:
super_trend_runner.send_trade_decision_via_email('merp')

SMTPResponseException: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials e5-20020ac86705000000b003a611cb2a95sm922457qtp.9 - gsmtp')

In [3]:
trade_data = super_trend_runner.read_trade_data_from_mongo_to_dataframe()
trade_data.tail(5)

,_id,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,high-low,...,average_true_range,high_low_avg,lower_band,higher_band,super_trend,final_higher_band,final_lower_band,buy_or_sell,portfolio_values,percentage_change
123,63b73f3f7cb8be1942f9323a,2022-12-30,190.179993,191.270004,189.279999,191.190002,5978800,0.0,0,1.990005,...,3.304510,190.275002,182.013727,198.536276,197.776727,197.776727,184.295412,False,10212.168634,0.0
124,63b73f3f7cb8be1942f9323b,2023-01-03,192.380005,193.360001,188.929993,190.410004,4092500,0.0,0,4.430008,...,3.419765,191.144997,182.595584,199.694409,197.776727,197.776727,184.295412,False,10212.168634,0.0
125,63b73f3f7cb8be1942f9323c,2023-01-04,191.509995,193.059998,190.139999,192.100006,3852500,0.0,0,2.919998,...,3.194713,191.599998,183.613217,199.586780,197.776727,197.776727,184.295412,False,10212.168634,0.0
126,63b73f3f7cb8be1942f9323d,2023-01-05,191.220001,191.220001,189.460007,189.850006,4023523,0.0,0,1.759995,...,3.004095,190.340004,182.829767,197.850241,197.776727,197.776727,184.295412,False,10212.168634,0.0
127,63b7d506d135f1d8c42d7e1f,2023-01-05,191.220001,191.270004,189.460007,189.850006,4149000,0.0,0,1.809998,...,3.007666,190.365005,182.845840,197.884171,197.776727,197.776727,184.295412,False,10212.168584,0.0

In [5]:
import smtplib, ssl
from email.message import EmailMessage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

In [6]:
receiver_email = "vbafna@umich.edu"
sender_email = "vbafna@umich.edu"
password = "@Collingsworth5"

port = 587
smtp_server = "smtp.gmail.com"

msg = EmailMessage()
body = "hello mr. paneer"
msg.set_content(body)

msg['Subject'] = "Trade Decision"
msg['From'] = sender_email
msg['To'] = receiver_email

context = ssl.create_default_context()
with smtplib.SMTP(smtp_server, port) as server:
    server.ehlo()
    server.starttls(context=context)
    server.login(sender_email, password)
    server.send_message(msg)