In [1]:
from super_trend_lib import SuperTrendRunner
import pymongo

client = pymongo.MongoClient("mongodb+srv://new_user:new_user@super-trend.xltbo.mongodb.net/?retryWrites=true&w=majority")
db = client['super-trend']

In [15]:
db['VTI'].delete_many({})

In [14]:
JSON_PATH = '/root/projects/supertrend'
super_trend_runner = SuperTrendRunner(ticker='VTI', json_path=JSON_PATH, multiplier=2.5, debug_mode=True, rolling_period=14, initial_amount=10000)
super_trend_df = super_trend_runner.initialize_dataframe()
super_trend_df

generating super trend for VTI starting 2022-07-07 00:00:00 and ending 2023-01-05 00:00:00

,Open,High,Low,Close,Volume,Dividends,Stock Splits,high-low,Previous Close,high-previous_close,...,average_true_range,high_low_avg,lower_band,higher_band,super_trend,final_higher_band,final_lower_band,buy_or_sell,portfolio_values,percentage_change
Date,,,,,,,,,,,,,,,,,,,,,
2022-07-07,190.895315,193.461988,190.855667,193.075500,2919300,0.0,0,2.606321,189.943970,3.518018,...,NaN,192.158827,NaN,NaN,NaN,NaN,NaN,None,10000.000000,0.0
2022-07-08,192.312445,193.937676,191.271898,192.877319,2799200,0.0,0,2.665778,193.075500,0.862175,...,NaN,192.604787,NaN,NaN,NaN,NaN,NaN,None,10000.000000,0.0
2022-07-11,191.638563,192.005227,190.082694,190.439453,3033800,0.0,0,1.922532,192.877319,-0.872093,...,NaN,191.043961,NaN,NaN,NaN,NaN,NaN,None,10000.000000,0.0
2022-07-12,190.270991,191.499830,187.892609,188.794403,2640300,0.0,0,3.607220,190.439453,1.060376,...,NaN,189.696219,NaN,NaN,NaN,NaN,NaN,None,10000.000000,0.0
2022-07-13,186.098899,189.369184,185.702507,187.971878,3322400,0.0,0,3.666678,188.794403,0.574781,...,NaN,187.535846,NaN,NaN,NaN,NaN,NaN,None,10000.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-29,189.490005,192.160004,189.369995,191.679993,5425700,0.0,0,2.790009,188.220001,3.940002,...,3.319467,190.764999,182.466332,199.063667,197.776727,197.776727,184.295412,False,10212.168634,0.0
2022-12-30,190.179993,191.270004,189.279999,191.190002,5978800,0.0,0,1.990005,191.679993,-0.409988,...,3.304510,190.275002,182.013727,198.536276,197.776727,197.776727,184.295412,False,10212.168634,0.0
2023-01-03,192.380005,193.360001,188.929993,190.410004,4092500,0.0,0,4.430008,191.190002,2.169998,...,3.419765,191.144997,182.595584,199.694409,197.776727,197.776727,184.295412,False,10212.168634,0.0
2023-01-04,191.509995,193.059998,190.139999,192.100006,3852500,0.0,0,2.919998,190.410004,2.649994,...,3.194713,191.599998,183.613217,199.586780,197.776727,197.776727,184.295412,False,10212.168634,0.0
2023-01-05,191.220001,191.220001,189.460007,189.850006,4023523,0.0,0,1.759995,192.100006,-0.880005,...,3.004095,190.340004,182.829767,197.850241,197.776727,197.776727,184.295412,False,10212.168634,0.0

In [16]:
super_trend_runner.write_initial_dataframe_to_mongo(super_trend_df)

In [17]:
trade_data = super_trend_runner.read_trade_data_from_mongo_to_dataframe()
trade_data.tail(5)

,_id,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,high-low,...,average_true_range,high_low_avg,lower_band,higher_band,super_trend,final_higher_band,final_lower_band,buy_or_sell,portfolio_values,percentage_change
122,63b73f3f7cb8be1942f93239,2022-12-29,189.490005,192.160004,189.369995,191.679993,5425700,0.0,0,2.790009,...,3.319467,190.764999,182.466332,199.063667,197.776727,197.776727,184.295412,False,10212.168634,0.0
123,63b73f3f7cb8be1942f9323a,2022-12-30,190.179993,191.270004,189.279999,191.190002,5978800,0.0,0,1.990005,...,3.304510,190.275002,182.013727,198.536276,197.776727,197.776727,184.295412,False,10212.168634,0.0
124,63b73f3f7cb8be1942f9323b,2023-01-03,192.380005,193.360001,188.929993,190.410004,4092500,0.0,0,4.430008,...,3.419765,191.144997,182.595584,199.694409,197.776727,197.776727,184.295412,False,10212.168634,0.0
125,63b73f3f7cb8be1942f9323c,2023-01-04,191.509995,193.059998,190.139999,192.100006,3852500,0.0,0,2.919998,...,3.194713,191.599998,183.613217,199.586780,197.776727,197.776727,184.295412,False,10212.168634,0.0
126,63b73f3f7cb8be1942f9323d,2023-01-05,191.220001,191.220001,189.460007,189.850006,4023523,0.0,0,1.759995,...,3.004095,190.340004,182.829767,197.850241,197.776727,197.776727,184.295412,False,10212.168634,0.0